<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="inlen8520085273" failures="1" tests="1" name="ParaBankRegisterTest" time="14.855" errors="0" timestamp="2023-07-10T22:05:42 IST">
  <testcase classname="testCases.TC_001_AccountRegistrationTest" name="test_account_Registration" time="7.46">
    <failure type="java.lang.AssertionError" message="TestFailed expected [Your account was created successfully. You are now logged in.] but found [If you have an account with us you can sign-up for free instant online access. You will have to provide some personal information.]">
      <![CDATA[java.lang.AssertionError: TestFailed expected [Your account was created successfully. You are now logged in.] but found [If you have an account with us you can sign-up for free instant online access. You will have to provide some personal information.]
at testCases.TC_001_AccountRegistrationTest.test_account_Registration(TC_001_AccountRegistrationTest.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test_account_Registration -->
  <testcase classname="testCases.TC_002_LoginTest" name="test_Login" time="0.0">
    <ignored/>
  </testcase> <!-- test_Login -->
</testsuite> <!-- ParaBankRegisterTest -->
